### ISSUE TITLE
live service 

### ISSUE THREAD

**Issue by stwalsh** [dwp/dwp-style-guide#13]
Worth an entry covering use of this, given 'full service' is in there?
I'm looking at an agent-side switch to-do where it's necessary, but had a moment of uncertainty on capitalisation, and whether it should be used at all.

**Comment by JohnTurnbull99** [comment]
Create a cross-reference entry for live service referring back to the full service entry.

Revise full service entry to say something along the lines of:

Avoid using either term. Sometimes you may need to use it internally if there's a danger of not being clear which service you're referring to. Never use externally.

Don't capitalise.

**Comment by JohnTurnbull99** [comment]
Some issue raised by Dean Smith and recorded here:
https://wiki.digital.uc.dwp.gov.uk/pages/editpage.action?pageId=50928205

Consider those before submitting to style council.
