### ISSUE TITLE
Should we ever use bold?

### ISSUE THREAD

**Issue by stwalsh** [dwp/dwp-style-guide#33]
A large topic. 

Should we ever use bold?

Your options include but are not limited to:

* hardline 'no' - classic GOV.UK
* conditional 'yes' - only for certain elements or when strictly defined criteria are met. 
* free and easy - if it feels important, **bold it**!

Slack discussion that triggered this pasted in comments.

**Comment by stwalsh** [comment]
John T:

> 
> Question: have we ever stated a position/fought a battle on the misuse of bold text in UCFS?
> Background: I proposed that the 'Due by' date should be at the top, as per the first 2 screenshots, and non-bold. My colleague agreed but said that it should be bold (like the third screenshot), because it's important, and because it could get confused with the 'created by' date immediately above it . I said a) GDS sez no to bold, b) it's in a bigger font size, and c) the 'created by' date will by definition always be in the past (apart from the day it's created) so can't be confused for the due by date (and if it is, they will think it's overdue and look into it further rather than ignore it).

Sean:

> 
> We’ve discussed it a little, but never taken the fight out to the service that I know of. 
> I say ‘discussed it’ - it may just have been me and Oates thrashing it out. He was hardline anti-bold, whereas I think it has some uses - albeit narrow ones. 
> istr he persuaded me. I think ‘don’t open the bold floodgates’ is an argument that always makes me pause. 
> Basically agree with your analysis.
> 
> fwiw I think the persuasive use case for bold is picking out information when you might be looking back and forth between phone and screen, or paper and screen - a code you enter, something like that. We can imagine different, better design solutions to that perhaps, but bold seems to be an effective and tested way to get that glanceable quality (which isn’t equivalent to ‘importance’). I don’t think the accessibility cost would be high as long as it’s used carefully; but I don’t think it would be used carefully and the ‘floodgates’ argument wins.

**Comment by stwalsh** [comment]
We'll need examples of:

* where bold is already used in the service
* places where we might effectively use bold 

We would need to test bold vs other means of emphasis. 

May be good for dyslexia.

**Comment by JohnTurnbull99** [comment]
See: https://trello.com/c/zUANnO00/927-should-we-ever-use-bold
