### ISSUE TITLE
Award, entitlement, benefit, payment…

### ISSUE THREAD

**Issue by stwalsh** [dwp/dwp-style-guide#36]
A huge issue, which obviously runs through all DWP work in every channel. 

Basically, do we have a sensitive, clearly defined and consistent vocabulary for the money we pay out?

Can we establish one?

Slack conversation pasted below as a starter. 

Relates to:

https://github.com/dwp/dwp-style-guide/issues/35

**Comment by stwalsh** [comment]
Anonymised Slack conversation 24/5/18

DS:
The PIP policy and comms people tend refer to someone's ongoing PIP payment as an 'award', eg in letters. Does anyone know if this is used for other benefits?

NM:
I think that’s standard […]
I think they used to say that on Tax Credits

MB:
I don't like award either. I sounds like someone has to be deemed worthy of it by someone else when it's actually an entitlement.

DS:
[…]know what you mean. It's also not used anywhere in mainstream public content on GOV.UK, so when it creeps in it feels unfamiliar.

**Comment by stwalsh** [comment]
Next actions 

* gather UC examples from the service and from the alps and from the letters
* get Slack opinions - what are the other services doing?

**Comment by stwalsh** [comment]
Some notes from issue 35, which we're closing as it's a subset of this.

From Helen Frith on Slack:

> ...do you know if there's a hard and fast rule about referring to UC as a benefit? Would 'payment' be a better term?

Andy Long replied

> I think the standard line is 'monthly payment'. There'll be people moving onto UC from tax credits, and HMRC spent an awful long time telling people that tax credits aren't benefits, so think 'payment' is a better description for UC.

Complication: we refer to 'other benefits' here and there, which implies that UC is itself a benefit. Do we need to change that or can live with the fuzziness?

**Comment by JohnTurnbull99** [comment]
See: https://trello.com/c/w0AOYzJk/925-awards-entitlements-or-benefits
