### ISSUE TITLE
When does an application become a claim?

### ISSUE THREAD

**Issue by DebStevenson** [dwp/dwp-style-guide#38]
We've mentioned 'application' in the style guide but haven't mentioned when to use 'claim'. Should this be added?

**Comment by stwalsh** [comment]
We need a draft entry clarifying difference between the two - the initial application vs the ongoing claim.
You apply to claim UC. 
If we want precision, we'll need a policy/PO steer on the exact point where application becomes claim (declaration vs IEI vs ???).
Check with other DWP services so we get the bigger picture.

**Comment by JohnTurnbull99** [comment]
See: https://trello.com/c/LqtaYa4T/926-when-does-an-application-become-a-claim

**Comment by eknodule** [comment]
FWIW it's referred to as a claim consistently throughout the Welfare Reform Act 2012 (+revs) and the only use of application as a noun is '_the action of putting something into operation_', but it is **not** used as a noun to mean '_a formal request to be considered for a position or to be allowed to do or have something, submitted to an authority, institution, or organization._'

**Comment by eknodule** [comment]
We refer to the process of requesting to be on universal credit as an application on only 3/~100 pages of the gather whereas we refer to it as a claim nearly 40/100 times (inc. error message pages)
