### ISSUE TITLE
Difference in use claim and account

### ISSUE THREAD

**Issue by Michelehowe** [dwp/dwp-style-guide#47]
Barry C. comment on you have a claim on an account. Needs clear definition of when we use claim and when we use account.

**Comment by stwalsh** [comment]
Account = the online account.
Claim = your application + contract etc that means you get support from UC

You can have more than one claim (split, join, leave UC and come back), but you only need one account.

### also 

We think 'online account' is fine, especially in email/sms. Slack chat:

P1: Hi all - so we quite often say 'You need to sign in to your online account'. I think 'You need to sign in to your account' is better. Would you agree?

P2: I seem to recall there was some research that said a number of people don't realise that Universal Credit is online. I don't remember the exact statistic, sorry. But if this is the case, there would be an argument for keeping 'online'.

P3: It might be helpful for those who are switching from live service. Maybe check with Andy Long if he has noticed this?

P4: I’ve always thought of ‘online’ being an extra little prompt to make someone go ‘oh yeah that thing’.
I’ve got half a hunch that ‘account’ and ‘sign in’ are quite  fuzzy words for people low on the digital inclusion scale.
