### ISSUE TITLE
Wording for phone appointment to-dos

### ISSUE THREAD

**Issue by jim-laney** [dwp/dwp-style-guide#49]
Claimants are told to 'attend' a phone appointment in multiple to-dos, for example 'Attend your commitments review by phone'. This is confusing.

Possible alternatives: Expect, Prepare for, Be ready for, Answer the call, Take part in...

**Comment by Michelehowe** [comment]
I worked on one of these recently. Revised to 'take part in ...'.

**Comment by AngelaMoore** [comment]
Can we change the ....by phone to (phone meeting) or something?

**Comment by Michelehowe** [comment]
This has been changed to 'Take part in your work search review by phone' and passed to devs.

**Comment by JohnTurnbull99** [comment]
This is something for the content patterns doc
