### ISSUE TITLE
National, citizen, resident

### ISSUE THREAD

**Issue by JohnTurnbull99** [dwp/dwp-style-guide#61]
Lower case when used in 'you are an EEA national', 'you are a UK national' etc

**Comment by JohnTurnbull99** [comment]
Needs a quick bit of research into differences/overlaps between 'national', 'citizen' and 'resident'.

**Comment by JohnTurnbull99** [comment]
See: https://trello.com/c/XMr9MoeK/1014-national-citizen-resident

**Comment by eknodule** [comment]
A national refers to many different categories of people, with varying connections to the UK, but includes British Citizens.

A citizen depends on what it is connected to, but a BRITISH citizen (in this exact wording) will have the right to live in the UK

A resident means an individual has the right to live in the UK.

**Comment by eknodule** [comment]
Also

All British Citizens are British Nationals, but not all British Nationals are British Citizens.
British Nationals are most commonly referred to (in Acts of Parliament) as any of the following:

British Citizens;
British Nationals (Overseas);
British Overseas Citizens;
British Overseas Territories Citizens;
British Protected Persons; or
British Subjects
Not all of these will have right of abode in the UK and apart from British Subjects, all are Commonwealth Citizens.

Don't even think about digging deeper as it's incredibly complex.

Some of the above are weird relics of old law (eg a British Protected Person is someone born in a country whose external affairs and defence were under British control).

So national is a huge umbrella.
