### ISSUE TITLE
Jobcentre (Plus)/service centre

### ISSUE THREAD

**Issue by LAMussel** [dwp/dwp-style-guide#68]
The capitalisation of jobcentre and service centre is varied in the service. We also sometimes use Jobcentre, and other times Jobcentre Plus. 

**Current notes in style guide:**

jobcentres
>Use “jobcentre” for a single building.
>Use “Jobcentre Plus” for the whole organisation.
>Don’t use “job centre”, JCP or Jobcentreplus.

Do we need to extend this to make it clearer? Assuming this is what we think:

**When the location is included ---**

Select Canterbury Service Centre
Select Sutton Jobcentre Plus

**When referenced generally ---**

Select a service centre
Select a jobcentre

You should contact the service centre.
You may need to bring some evidence to a jobcentre to prove this.

**Comment by JohnTurnbull99** [comment]
Find some examples of where/how we refer to jobcentres in the service. Lucy's approach looks right, but is there a case for allowing exceptions in certain contexts (eg agent-facing dropdown lists)?

**Comment by JohnTurnbull99** [comment]
https://trello.com/c/RAGXOGnb/1007-jobcentre-plus-service-centre
