### ISSUE TITLE
Joint claims: Firstname and Firstname Vs. Firstname Secondname and Firstname Secondname 

### ISSUE THREAD

**Issue by eknodule** [dwp/dwp-style-guide#70]
We seem to prefer 'Tom Jackson and Tina Jackson' to 'Tom and Tina' when referring to joint claims. 

As a recent new starter it would have been useful if this was in the style guide under 'Joint claims'

**Comment by JohnTurnbull99** [comment]
We always use firstname lastname for both claimants in this scenario.

Same for single claimants.

Angela to check (plus reasons) and we add to content patterns.
